options:
  merge-default-rules: false
  max-warnings: 50
files:
  include: 'src/styles/**/*.s+(a|c)ss'
rules:
  declarations-before-nesting: 1
  extends-before-declarations: 1
  final-newline: 1
  max-line-length:
    - 1
    -
      length: 140
  no-color-hex: 1
  no-duplicate-properties: 1
  no-empty-rulesets: 1
  no-mergeable-selectors: 1
  no-misspelled-properties: 1
  no-trailing-whitespace: 1
  one-declaration-per-line: 1
  single-line-per-selector: 1
  indentation:
    - 1
    -
      size: 2
  space-after-colon: 1
  space-after-comma: 1
