dist: trusty
sudo: required
language: node_js
node_js:
  - "7"
os:
  - linux

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start

install:
  - npm install

script:
  - npm test
